In [1]:
# pubchem finger print
import pandas as pd 
df3 =pd.read_csv('coronavirus_bioactivity_data_2class_pIC50_120.csv') 
# df3
df3.loc[df3.molecule_chembl_id == "CHEMBL370923"]

,Unnamed: 0,molecule_chembl_id,canonical_smiles,class,MW,LogP,NumHDonors,NumHAcceptors,pIC50
7,11,CHEMBL370923,O=C1C(=O)N(Cc2ccc(C(=O)N3CCCCC3)s2)c2ccc(I)cc21,inactive,480.327,3.7083,0.0,4.0,4.756962

In [2]:
selection =['canonical_smiles','molecule_chembl_id']
df3_selection = df3[selection]
# df3_selection
df3_selection.to_csv("molecule.smi", sep ="\t", index =False ,header =False)

In [ ]:
'''padel.sh is a file which allows us to give us molecular finger print of each canonical smiles , these codes did not ran in 
jupitor notbook so that part of analysis was done in windows subsystem linux'''

In [8]:
'''first the padel.sh was downloaded from 
! wget https://github.com/dataprofessor/bioinformatics/raw/master/padel.zip
! wget https://github.com/dataprofessor/bioinformatics/raw/master/padel.sh
and "df3_selection" was used as an input for padel.sh
the output came out to be descriptors_output.csv'''

'first the padel.sh was downloaded from \n! wget https://github.com/dataprofessor/bioinformatics/raw/master/padel.zip\n! wget https://github.com/dataprofessor/bioinformatics/raw/master/padel.sh\nand df3_selection was used as an input for padel.sh\nthe output came out to be descriptors_output.csv'

In [5]:
df3_x = pd.read_csv("descriptors_output.csv")
df3_x

,Name,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,CHEMBL370923,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,CHEMBL426082,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,CHEMBL185698,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CHEMBL191575,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,CHEMBL365469,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,CHEMBL2146517,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
73,CHEMBL45830,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
74,CHEMBL363535,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
75,CHEMBL227075,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
76,CHEMBL215254,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
# df3_x = df3_x.drop(column = ["Name"])

In [8]:
# df3.to_csv("corona_pubchem_fp.csv",index =False)

In [10]:
pic50 = []
for i in df3_x["Name"]:
    pic51 = df3.loc[df3["molecule_chembl_id"] == f"{i}" , "pIC50"].values[0]
    pic50.append(pic51)

In [11]:
pic50 = pd.Series(pic50, name = "pIC50")
df3_x = pd.concat([df3_x,pic50],axis = 1)

In [12]:
df = df3_x.drop(columns = "Name")
df

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880,pIC50
0,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.756962
1,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.882397
2,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.869666
3,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.900665
4,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.950782
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.675718
73,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.675718
74,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.412289
75,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.841638
76,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.605548

In [13]:
df.to_csv("dataset_final_molfin_ic50.csv")

In [19]:
# y variable 
# df3_y = df3_x.pIC50
# df3_y

In [20]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\makerofdreams\anaconda3\lib\site-packages (1.2.2)
Requirement already satisfied: numpy>=1.17.3 in c:\users\makerofdreams\anaconda3\lib\site-packages (from scikit-learn) (1.24.3)
Requirement already satisfied: scipy>=1.3.2 in c:\users\makerofdreams\anaconda3\lib\site-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\makerofdreams\anaconda3\lib\site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\makerofdreams\anaconda3\lib\site-packages (from scikit-learn) (2.2.0)

In [21]:
'''model training and model building'''
import pandas as pd 
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

In [22]:
x = df.drop("pIC50",axis = 1)
x

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
73,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
74,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
75,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
76,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [23]:
x.shape

(77, 881)

In [24]:
from sklearn.feature_selection import VarianceThreshold
selection = VarianceThreshold(threshold =(.8 * (1-.8)))
x =selection.fit_transform(x)

In [29]:
# x.shape
y = df.pIC50
y

0    4.76
1    4.88
2    4.87
3    4.90
4    4.95
     ...
72   4.68
73   4.68
74   4.41
75   4.84
76   4.61
Name: pIC50, Length: 77, dtype: float64

In [45]:
#data split (80/20) ratio
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2)

In [46]:
x_train.shape

(61, 192)

In [47]:
import numpy as np 
np.random.seed(100)
model = RandomForestRegressor(n_estimators = 100)
model.fit(x_train, y_train)
r2 = model.score(x_test,y_test)
r2

0.5281633920760774